def schema_to_ddl(d):
    return ", ".join(f"`{c}` {t}" for c, t in d.items())


TABLE_SCHEMAS = {
    # ── dimensions ──────────────────────────────────────────────────────
    "dim_locations": {
        "location_id": "BIGINT",
        "location_code": "STRING",
        "name": "STRING",
        "type": "STRING",
        "street": "STRING",
        "city": "STRING",
        "region": "STRING",
        "postal_code": "STRING",
        "latitude": "DOUBLE",
        "longitude": "DOUBLE",
        "phone": "STRING",
        "email": "STRING",
        "manager_id": "BIGINT",
        "number_of_bays": "BIGINT",
        "area_m2": "BIGINT",
        "opening_date": "DATE",
        "is_active": "BOOLEAN",
    },
    "dim_employees": {
        "employee_id": "BIGINT",
        "employee_code": "STRING",
        "first_name": "STRING",
        "last_name": "STRING",
        "national_id": "STRING",
        "position": "STRING",
        "location_id": "BIGINT",
        "hire_date": "DATE",
        "termination_date": "DATE",
        "hourly_rate": "DOUBLE",
        "is_active": "BOOLEAN",
    },
    "dim_customers": {
        "customer_id": "BIGINT",
        "customer_code": "STRING",
        "customer_type": "STRING",
        "first_name": "STRING",
        "last_name": "STRING",
        "company_name": "STRING",
        "tax_id": "STRING",
        "email": "STRING",
        "phone": "STRING",
        "city": "STRING",
        "postal_code": "STRING",
        "registration_date": "DATE",
        "preferred_location_id": "BIGINT",
        "marketing_consent": "BOOLEAN",
    },
    "dim_vehicles": {
        "vehicle_id": "BIGINT",
        "customer_id": "BIGINT",
        "make": "STRING",
        "model": "STRING",
        "year": "BIGINT",
        "vin": "STRING",
        "registration_number": "STRING",
        "fuel_type": "STRING",
        "engine_displacement": "DOUBLE",
        "horsepower": "BIGINT",
        "color": "STRING",
        "mileage_km": "BIGINT",
        "first_registration_date": "DATE",
    },
    "dim_products": {
        "product_id": "BIGINT",
        "product_code": "STRING",
        "name": "STRING",
        "category": "STRING",
        "manufacturer": "STRING",
        "purchase_price_net": "DOUBLE",
        "sale_price_net": "DOUBLE",
        "vat_rate": "BIGINT",
        "unit": "STRING",
        "weight_kg": "DOUBLE",
        "min_stock_level": "BIGINT",
        "is_active": "BOOLEAN",
    },
    "dim_services": {
        "service_id": "BIGINT",
        "service_code": "STRING",
        "name": "STRING",
        "category": "STRING",
        "min_price_net": "BIGINT",
        "max_price_net": "BIGINT",
        "estimated_time_min": "BIGINT",
        "is_active": "BOOLEAN",
    },
    "dim_suppliers": {
        "supplier_id": "BIGINT",
        "supplier_code": "STRING",
        "name": "STRING",
        "tax_id": "STRING",
        "city": "STRING",
        "address": "STRING",
        "postal_code": "STRING",
        "phone": "STRING",
        "email": "STRING",
        "contact_person": "STRING",
        "payment_terms_days": "BIGINT",
        "min_order_value": "DOUBLE",
        "is_active": "BOOLEAN",
    },
    # ── facts ────────────────────────────────────────────────────────────
    "fact_work_orders": {
        "work_order_id": "BIGINT",
        "work_order_code": "STRING",
        "location_id": "INT",
        "customer_id": "INT",
        "vehicle_id": "INT",
        "mechanic_id": "INT",
        "reception_date": "DATE",
        "completion_date": "DATE",
        "status": "STRING",
        "mileage_at_reception": "INT",
        "customer_notes": "STRING",
        "year": "INT",
        "month": "INT",
    },
    "fact_work_order_items": {
        "wo_item_id": "BIGINT",
        "work_order_id": "BIGINT",
        "item_type": "STRING",
        "service_id": "INT",
        "product_id": "INT",
        "quantity": "INT",
        "unit_price_net": "DOUBLE",
        "value_net": "DOUBLE",
        "vat_rate": "INT",
        "value_gross": "DOUBLE",
        "discount_percent": "INT",
    },
    "fact_sales_transactions": {
        "transaction_id": "BIGINT",
        "transaction_code": "STRING",
        "location_id": "INT",
        "customer_id": "INT",
        "employee_id": "INT",
        "transaction_date": "TIMESTAMP",
        "payment_method": "STRING",
        "receipt_number": "STRING",
        "year": "INT",
        "month": "INT",
    },
    "fact_sales_items": {
        "sales_item_id": "BIGINT",
        "transaction_id": "BIGINT",
        "product_id": "INT",
        "quantity": "INT",
        "unit_price_net": "DOUBLE",
        "discount_percent": "INT",
        "value_net": "DOUBLE",
        "vat_rate": "INT",
        "value_gross": "DOUBLE",
    },
    "fact_invoices": {
        "invoice_id": "BIGINT",
        "invoice_code": "STRING",
        "document_type": "STRING",
        "source_type": "STRING",
        "source_id": "BIGINT",
        "customer_id": "INT",
        "location_id": "INT",
        "issue_date": "DATE",
        "sale_date": "DATE",
        "payment_due_date": "DATE",
        "value_net": "DOUBLE",
        "value_vat": "DOUBLE",
        "value_gross": "DOUBLE",
        "status": "STRING",
        "year": "INT",
        "month": "INT",
    },
    "fact_payments": {
        "payment_id": "BIGINT",
        "invoice_id": "BIGINT",
        "payment_date": "DATE",
        "amount": "DOUBLE",
        "payment_method": "STRING",
        "status": "STRING",
        "transaction_number": "STRING",
        "year": "INT",
        "month": "INT",
    },
    "fact_inventory_movements": {
        "movement_id": "BIGINT",
        "product_id": "INT",
        "location_id": "INT",
        "movement_type": "STRING",
        "quantity": "INT",
        "movement_date": "DATE",
        "source_document": "STRING",
        "document_number": "STRING",
        "value_net": "DOUBLE",
        "notes": "STRING",
        "year": "INT",
        "month": "INT",
    },
    "fact_appointments": {
        "appointment_id": "BIGINT",
        "customer_id": "INT",
        "vehicle_id": "INT",
        "location_id": "INT",
        "service_id": "INT",
        "booking_date": "DATE",
        "appointment_date": "TIMESTAMP",
        "status": "STRING",
        "booking_channel": "STRING",
        "notes": "STRING",
        "year": "INT",
        "month": "INT",
    },
    "fact_purchase_orders": {
        "po_id": "BIGINT",
        "po_code": "STRING",
        "supplier_id": "INT",
        "location_id": "INT",
        "order_date": "DATE",
        "planned_delivery_date": "DATE",
        "actual_delivery_date": "DATE",
        "value_net": "DOUBLE",
        "value_gross": "DOUBLE",
        "status": "STRING",
        "year": "INT",
    },
    "fact_purchase_order_items": {
        "po_item_id": "BIGINT",
        "po_id": "BIGINT",
        "product_id": "INT",
        "quantity_ordered": "INT",
        "quantity_delivered": "INT",
        "unit_price_net": "DOUBLE",
        "value_net": "DOUBLE",
    },
    "fact_customer_feedback": {
        "feedback_id": "BIGINT",
        "customer_id": "INT",
        "location_id": "INT",
        "work_order_id": "BIGINT",
        "feedback_date": "DATE",
        "rating": "INT",
        "comment": "STRING",
        "category": "STRING",
        "channel": "STRING",
    },
    "fact_loyalty_program": {
        "loyalty_id": "BIGINT",
        "customer_id": "INT",
        "event_date": "DATE",
        "event_type": "STRING",
        "points": "INT",
        "description": "STRING",
        "balance_after": "INT",
        "tier": "STRING",
    },
    "fact_employee_schedules": {
        "schedule_id": "BIGINT",
        "employee_id": "INT",
        "date": "DATE",
        "start_hour": "INT",
        "end_hour": "INT",
        "shift_type": "STRING",
        "overtime_hours": "INT",
        "attendance": "STRING",
    },
}

# fact tables that carry partition columns in their parquet directory structure
PARTITIONED_TABLES = {
    "fact_work_orders": ["year", "month"],
    "fact_sales_transactions": ["year", "month"],
    "fact_invoices": ["year", "month"],
    "fact_payments": ["year", "month"],
    "fact_inventory_movements": ["year", "month"],
    "fact_appointments": ["year", "month"],
    "fact_purchase_orders": ["year"],
}

print(f"Schemas loaded: {len(TABLE_SCHEMAS)} tables")