TABLE_SCHEMAS = {
    # ── wymiarowe ───────────────────────────────────────────────────────
    "dim_locations": {
        "location_id": "BIGINT",
        "location_code": "STRING",
        "nazwa": "STRING",
        "typ": "STRING",
        "ulica": "STRING",
        "miasto": "STRING",
        "wojewodztwo": "STRING",
        "kod_pocztowy": "STRING",
        "latitude": "DOUBLE",
        "longitude": "DOUBLE",
        "telefon": "STRING",
        "email": "STRING",
        "kierownik_id": "BIGINT",
        "liczba_stanowisk": "BIGINT",
        "powierzchnia_m2": "BIGINT",
        "data_otwarcia": "DATE",
        "czy_aktywna": "BOOLEAN",
    },
    "dim_employees": {
        "employee_id": "BIGINT",
        "employee_code": "STRING",
        "imie": "STRING",
        "nazwisko": "STRING",
        "pesel": "STRING",
        "stanowisko": "STRING",
        "location_id": "BIGINT",
        "data_zatrudnienia": "DATE",
        "data_zwolnienia": "DATE",
        "stawka_godzinowa": "DOUBLE",
        "czy_aktywny": "BOOLEAN",
    },
    "dim_customers": {
        "customer_id": "BIGINT",
        "customer_code": "STRING",
        "typ_klienta": "STRING",
        "imie": "STRING",
        "nazwisko": "STRING",
        "nazwa_firmy": "STRING",
        "nip": "STRING",
        "email": "STRING",
        "telefon": "STRING",
        "miasto": "STRING",
        "kod_pocztowy": "STRING",
        "data_rejestracji": "DATE",
        "preferowana_lokalizacja_id": "BIGINT",
        "zgoda_marketing": "BOOLEAN",
    },
    "dim_vehicles": {
        "vehicle_id": "BIGINT",
        "customer_id": "BIGINT",
        "marka": "STRING",
        "model": "STRING",
        "rocznik": "BIGINT",
        "vin": "STRING",
        "nr_rejestracyjny": "STRING",
        "typ_paliwa": "STRING",
        "pojemnosc_silnika": "DOUBLE",
        "moc_km": "BIGINT",
        "kolor": "STRING",
        "przebieg_km": "BIGINT",
        "data_pierwszej_rejestracji": "DATE",
    },
    "dim_products": {
        "product_id": "BIGINT",
        "product_code": "STRING",
        "nazwa": "STRING",
        "kategoria": "STRING",
        "producent": "STRING",
        "cena_zakupu_netto": "DOUBLE",
        "cena_sprzedazy_netto": "DOUBLE",
        "vat_procent": "BIGINT",
        "jednostka": "STRING",
        "waga_kg": "DOUBLE",
        "min_stan_magazynowy": "BIGINT",
        "czy_aktywny": "BOOLEAN",
    },
    "dim_services": {
        "service_id": "BIGINT",
        "service_code": "STRING",
        "nazwa": "STRING",
        "kategoria": "STRING",
        "cena_min_netto": "BIGINT",
        "cena_max_netto": "BIGINT",
        "szacowany_czas_min": "BIGINT",
        "czy_aktywna": "BOOLEAN",
    },
    "dim_suppliers": {
        "supplier_id": "BIGINT",
        "supplier_code": "STRING",
        "nazwa": "STRING",
        "nip": "STRING",
        "miasto": "STRING",
        "adres": "STRING",
        "kod_pocztowy": "STRING",
        "telefon": "STRING",
        "email": "STRING",
        "osoba_kontaktowa": "STRING",
        "warunki_platnosci_dni": "BIGINT",
        "min_wartosc_zamowienia": "DOUBLE",
        "czy_aktywny": "BOOLEAN",
    },
    # ── faktowe ─────────────────────────────────────────────────────────
    "fact_work_orders": {
        "work_order_id": "BIGINT",
        "work_order_code": "STRING",
        "location_id": "BIGINT",
        "customer_id": "BIGINT",
        "vehicle_id": "BIGINT",
        "mechanic_id": "BIGINT",
        "data_przyjecia": "DATE",
        "data_zakonczenia": "DATE",
        "status": "STRING",
        "przebieg_przy_przyjecia": "BIGINT",
        "uwagi_klienta": "STRING",
        "rok": "BIGINT",
        "miesiac": "BIGINT",
    },
    "fact_work_order_items": {
        "wo_item_id": "BIGINT",
        "work_order_id": "BIGINT",
        "typ_pozycji": "STRING",
        "service_id": "BIGINT",
        "product_id": "BIGINT",
        "ilosc": "BIGINT",
        "cena_jednostkowa_netto": "DOUBLE",
        "wartosc_netto": "DOUBLE",
        "vat_procent": "BIGINT",
        "wartosc_brutto": "DOUBLE",
        "rabat_procent": "BIGINT",
    },
    "fact_sales_transactions": {
        "transaction_id": "BIGINT",
        "transaction_code": "STRING",
        "location_id": "BIGINT",
        "customer_id": "BIGINT",
        "employee_id": "BIGINT",
        "data_transakcji": "DATE",
        "metoda_platnosci": "STRING",
        "nr_paragonu": "STRING",
        "rok": "BIGINT",
        "miesiac": "BIGINT",
    },
    "fact_sales_items": {
        "sales_item_id": "BIGINT",
        "transaction_id": "BIGINT",
        "product_id": "BIGINT",
        "ilosc": "BIGINT",
        "cena_jednostkowa_netto": "DOUBLE",
        "rabat_procent": "BIGINT",
        "wartosc_netto": "DOUBLE",
        "vat_procent": "BIGINT",
        "wartosc_brutto": "DOUBLE",
    },
    "fact_invoices": {
        "invoice_id": "BIGINT",
        "invoice_code": "STRING",
        "typ_dokumentu": "STRING",
        "source_type": "STRING",
        "source_id": "BIGINT",
        "customer_id": "BIGINT",
        "location_id": "BIGINT",
        "data_wystawienia": "DATE",
        "data_sprzedazy": "DATE",
        "termin_platnosci": "DATE",
        "wartosc_netto": "DOUBLE",
        "wartosc_vat": "DOUBLE",
        "wartosc_brutto": "DOUBLE",
        "status": "STRING",
        "rok": "BIGINT",
        "miesiac": "BIGINT",
    },
    "fact_payments": {
        "payment_id": "BIGINT",
        "invoice_id": "BIGINT",
        "data_platnosci": "DATE",
        "kwota": "DOUBLE",
        "metoda_platnosci": "STRING",
        "status": "STRING",
        "numer_transakcji": "STRING",
        "rok": "BIGINT",
        "miesiac": "BIGINT",
    },
    "fact_inventory_movements": {
        "movement_id": "BIGINT",
        "product_id": "BIGINT",
        "location_id": "BIGINT",
        "typ_ruchu": "STRING",
        "ilosc": "BIGINT",
        "data_ruchu": "DATE",
        "dokument_zrodlowy": "STRING",
        "nr_dokumentu": "STRING",
        "wartosc_netto": "DOUBLE",
        "uwagi": "STRING",
        "rok": "BIGINT",
        "miesiac": "BIGINT",
    },
    "fact_appointments": {
        "appointment_id": "BIGINT",
        "customer_id": "BIGINT",
        "vehicle_id": "BIGINT",
        "location_id": "BIGINT",
        "service_id": "BIGINT",
        "data_rezerwacji": "DATE",
        "data_wizyty": "DATE",
        "status": "STRING",
        "kanal_rezerwacji": "STRING",
        "uwagi": "STRING",
        "rok": "BIGINT",
        "miesiac": "BIGINT",
    },
    "fact_purchase_orders": {
        "po_id": "BIGINT",
        "po_code": "STRING",
        "supplier_id": "BIGINT",
        "location_id": "BIGINT",
        "data_zamowienia": "DATE",
        "data_dostawy_planowana": "DATE",
        "data_dostawy_rzeczywista": "DATE",
        "wartosc_netto": "DOUBLE",
        "wartosc_brutto": "DOUBLE",
        "status": "STRING",
        "rok": "BIGINT",
    },
    "fact_purchase_order_items": {
        "po_item_id": "BIGINT",
        "po_id": "BIGINT",
        "product_id": "BIGINT",
        "ilosc_zamowiona": "BIGINT",
        "ilosc_dostarczona": "BIGINT",
        "cena_jednostkowa_netto": "DOUBLE",
        "wartosc_netto": "DOUBLE",
    },
    "fact_customer_feedback": {
        "feedback_id": "BIGINT",
        "customer_id": "BIGINT",
        "location_id": "BIGINT",
        "work_order_id": "BIGINT",
        "data_opinii": "DATE",
        "ocena": "BIGINT",
        "komentarz": "STRING",
        "kategoria": "STRING",
        "kanal": "STRING",
    },
    "fact_loyalty_program": {
        "loyalty_id": "BIGINT",
        "customer_id": "BIGINT",
        "data_zdarzenia": "DATE",
        "typ_zdarzenia": "STRING",
        "punkty": "BIGINT",
        "opis": "STRING",
        "saldo_po": "BIGINT",
        "poziom": "STRING",
    },
    "fact_employee_schedules": {
        "schedule_id": "BIGINT",
        "employee_id": "BIGINT",
        "data": "DATE",
        "godzina_start": "BIGINT",
        "godzina_koniec": "BIGINT",
        "typ_zmiany": "STRING",
        "nadgodziny_h": "BIGINT",
        "obecnosc": "STRING",
    },
}

# tabele faktowe z kolumnami partycji w strukturze katalogów parquet
PARTITIONED_TABLES = {
    "fact_work_orders": ["rok", "miesiac"],
    "fact_sales_transactions": ["rok", "miesiac"],
    "fact_invoices": ["rok", "miesiac"],
    "fact_payments": ["rok", "miesiac"],
    "fact_inventory_movements": ["rok", "miesiac"],
    "fact_appointments": ["rok", "miesiac"],
    "fact_purchase_orders": ["rok"],
}

try:
    from pyspark.sql.types import (
        StructType, StructField,
        LongType, StringType, DateType, DoubleType, BooleanType,
    )

    _TYPE_MAP = {
        "BIGINT":  LongType(),
        "STRING":  StringType(),
        "DATE":    DateType(),
        "DOUBLE":  DoubleType(),
        "BOOLEAN": BooleanType(),
    }

    def build_spark_schema(table_name: str) -> StructType:
        return StructType([
            StructField(col, _TYPE_MAP[dtype], nullable=True)
            for col, dtype in TABLE_SCHEMAS[table_name].items()
        ])

except ImportError:
    pass